accent = "#8BA4B0"
cursor = "#c8c093"
foreground = "#d5d2c4"
background = "#020408"
selection_foreground = "#c0bda8"
selection_background = "#181A22"

color0 = "#101218"
color1 = "#C4746E"
color2 = "#8A9A7B"
color3 = "#C4B28A"
color4 = "#8BA4B0"
color5 = "#A292A3"
color6 = "#8EA4A2"
color7 = "#d5d2c4"
color8 = "#9E9B93"
color9 = "#E46876"
color10 = "#87A987"
color11 = "#E6C384"
color12 = "#7FB4CA"
color13 = "#938AA9"
color14 = "#7AA89F"
color15 = "#d5d2c4"

# Extended palette (Kanso Neovim)
orange = "#b6927b"
orange2 = "#b98d7b"
blue2 = "#658594"
violet2 = "#8992a7"
gray3 = "#909398"
gray4 = "#75797f"
gray5 = "#5C6066"
