accent = "#8BA4B0"
cursor = "#c8c093"
foreground = "#dcd7ba"
background = "#020408"
selection_foreground = "#c0bda8"
selection_background = "#181A22"

color0 = "#101218"
color1 = "#de7168"
color2 = "#8bae79"
color3 = "#d4b480"
color4 = "#8abbcc"
color5 = "#b097b2"
color6 = "#8dbbb9"
color7 = "#dcd7ba"
color8 = "#adaaa1"
color9 = "#ff606d"
color10 = "#8ac48a"
color11 = "#f8cb77"
color12 = "#79cde9"
color13 = "#9a98c5"
color14 = "#77c2a9"
color15 = "#dcd7ba"

# Extended palette (Kanso Neovim)
orange = "#ce9776"
orange2 = "#d29275"
blue2 = "#629fa4"
violet2 = "#8a9fc0"
gray3 = "#9ea1a7"
gray4 = "#868b92"
gray5 = "#696e75"
